name: Docker Build

on: 
  pull_request:
    branches: 
      - master
      - feature/*
      - fix/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Via the Makefile, build the Docker image
      run: make build
